#! /bin/sh

# Test ISO C 99 <inttypes.h> format string directives with plural forms.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles fc4.tmp fc4.pot"
: ${XGETTEXT=xgettext}
${XGETTEXT} -o fc4.tmp --omit-header --no-location ${top_srcdir}/tests/format-c-4-prg.c
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < fc4.tmp > fc4.pot
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles fc4.ok"
cat <<EOF > fc4.ok
#, c-format
msgid "father of %<PRId8> child"
msgid_plural "father of %<PRId8> children"
msgstr[0] ""
msgstr[1] ""
EOF

: ${DIFF=diff}
${DIFF} fc4.ok fc4.pot || exit 1

tmpfiles="$tmpfiles de.po"
cat <<EOF > de.po
#, c-format
msgid "father of %<PRId8> child"
msgid_plural "father of %<PRId8> children"
msgstr[0] "Vater eines Kindes"
msgstr[1] "Vater von %<PRId8> Kindern"
EOF

tmpfiles="$tmpfiles de"
test -d de || mkdir de
test -d de/LC_MESSAGES || mkdir de/LC_MESSAGES

: ${MSGFMT=msgfmt}
${MSGFMT} -o de/LC_MESSAGES/fc4.mo de.po

tmpfiles="$tmpfiles de.po.tmp de.po.un"
: ${MSGUNFMT=msgunfmt}
${MSGUNFMT} -o de.po.tmp de/LC_MESSAGES/fc4.mo
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < de.po.tmp > de.po.un
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

: ${DIFF=diff}
${DIFF} de.po de.po.un || exit 1

LANGUAGE= ./fc4 de_DE
result=$?

rm -fr $tmpfiles

exit $result
