#! /bin/sh

# Test the gettext program with -e option.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

# Create binary test file in correct position.
tmpfiles="$tmpfiles gt-1"
test -d gt-1 || mkdir gt-1
test -d gt-1/LC_MESSAGES || mkdir gt-1/LC_MESSAGES
cp $top_srcdir/tests/test.mo gt-1/LC_MESSAGES

tmpfiles="$tmpfiles gt-test1.out"
: ${GETTEXT=gettext}
TEXTDOMAINDIR=. LANGUAGE=gt-1 \
${GETTEXT} --env LC_ALL=en -e test 'SYS_(C)\n' | LC_ALL=C tr -d '\r' > gt-test1.out

# Create correct file.
tmpfile="$tmpfiles gtmf-test1.ok"
cat <<EOF > gtmf-test1.ok
MSGFMT(1) portable message object file compiler
Copyright (C) 1995 Free Software Foundation
Report bugs to <bug-gnu-utils@gnu.org>
EOF

: ${DIFF=diff}
${DIFF} gtmf-test1.ok gt-test1.out
result=$?

rm -fr $tmpfiles

exit $result
