#! /bin/sh

# Test handling of input files with different translations:
# preserve all variants, add markers

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles mcat-test6.in1 mcat-test6.in2"
cat <<\EOF > mcat-test6.in1
# German message file for xyz.
# Copyright (C) 1999, 2000, 2001 xyz.
# Kab Def <ke@zzz.uucp>, 2000.
#
msgid ""
msgstr ""
"Project-Id-Version: xyz\n"
"POT-Creation-Date: 2001-04-24 12:51:34+0200\n"
"PO-Revision-Date: 2001-04-24 13:02+02:00\n"
"Last-Translator: Kab Def <ke@zzz.uucp>\n"
"Language-Team: German <i18n@zzz.uucp>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#. Help text (HTML-like) START
#: clients/inst_ask_config.ycp:119
msgid ""
"Congratulations!"
msgstr ""
"Glückwunsch!"
EOF

cat <<\EOF > mcat-test6.in2
# German message file for xyz.
# Copyright (C) 1999, 2000, 2001 xyz.
# Kab Def <ke@zzz.uucp>, 2000.
#
msgid ""
msgstr ""
"Project-Id-Version: xyz\n"
"POT-Creation-Date: 2001-04-24 12:51:34+0200\n"
"PO-Revision-Date: 2001-04-24 13:02+02:00\n"
"Last-Translator: Kab Def <ke@zzz.uucp>\n"
"Language-Team: German <i18n@zzz.uucp>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#. Help text (HTML-like) START
#: clients/inst_ask_config.ycp:119
msgid ""
"Congratulations!"
msgstr ""
"Herzlichen Glückwunsch!"
EOF

tmpfiles="$tmpfiles mcat-test6.tmp mcat-test6.out"
rm -f mcat-test6.tmp

: ${MSGCAT=msgcat}
${MSGCAT} --more-than=0 -o mcat-test6.tmp \
    mcat-test6.in1 mcat-test6.in2
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < mcat-test6.tmp > mcat-test6.out
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles mcat-test6.ok"
cat << \EOF > mcat-test6.ok
# German message file for xyz.
# Copyright (C) 1999, 2000, 2001 xyz.
# Kab Def <ke@zzz.uucp>, 2000.
#
msgid ""
msgstr ""
"Project-Id-Version: xyz\n"
"POT-Creation-Date: 2001-04-24 12:51:34+0200\n"
"PO-Revision-Date: 2001-04-24 13:02+02:00\n"
"Last-Translator: Kab Def <ke@zzz.uucp>\n"
"Language-Team: German <i18n@zzz.uucp>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#. Help text (HTML-like) START
#: clients/inst_ask_config.ycp:119
#, fuzzy
msgid "Congratulations!"
msgstr ""
"#-#-#-#-#  mcat-test6.in1 (xyz)  #-#-#-#-#\n"
"Glückwunsch!\n"
"#-#-#-#-#  mcat-test6.in2 (xyz)  #-#-#-#-#\n"
"Herzlichen Glückwunsch!"
EOF

: ${DIFF=diff}
${DIFF} mcat-test6.ok mcat-test6.out
result=$?

rm -fr $tmpfiles

exit $result
