#! /bin/sh

# Test --update: POT-Creation-Date changed. This change must not be reflected
# in the resulting PO file; this is needed for projects which don't put the
# .pot file under CVS.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles mm-u-3.po"
cat <<\EOF > mm-u-3.po
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: cog_training 1.0\n"
"POT-Creation-Date: 2001-04-29 22:40+0200\n"
"PO-Revision-Date: 2001-04-29 21:19+02:00\n"
"Last-Translator: Felix N. <xyz@zyx.uucp>\n"
"Language-Team: German <de@li.org>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: cogarithmetic.cc:12 cogidmarkup.cc:288 cogroman.cc:14
msgid "white"
msgstr "weiﬂ"
EOF

tmpfiles="$tmpfiles mm-u-3.pot"
cat <<EOF > mm-u-3.pot
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2001-04-30 18:51+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: cogarithmetic.cc:12 cogidmarkup.cc:288 cogroman.cc:14
msgid "white"
msgstr ""
EOF

tmpfiles="$tmpfiles mm-u-3.po~"
: ${MSGMERGE=msgmerge}
${MSGMERGE} -q --update mm-u-3.po mm-u-3.pot
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles mm-u-3.ok"
cat <<\EOF > mm-u-3.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: cog_training 1.0\n"
"POT-Creation-Date: 2001-04-29 22:40+0200\n"
"PO-Revision-Date: 2001-04-29 21:19+02:00\n"
"Last-Translator: Felix N. <xyz@zyx.uucp>\n"
"Language-Team: German <de@li.org>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: cogarithmetic.cc:12 cogidmarkup.cc:288 cogroman.cc:14
msgid "white"
msgstr "weiﬂ"
EOF

: ${DIFF=diff}
${DIFF} mm-u-3.ok mm-u-3.po
result=$?

rm -fr $tmpfiles

exit $result
