#!/bin/sh

# Test Tcl support: --add-comments option.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-t-3.tcl"
cat <<\EOF > xg-t-3.tcl
# a
set string [_ "hello world" # b
] # c
EOF

tmpfiles="$tmpfiles xg-t-3.tmp.po xg-t-3.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --add-comments --omit-header --no-location --keyword=_ \
  -d xg-t-3.tmp xg-t-3.tcl
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < xg-t-3.tmp.po > xg-t-3.po
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-t-3.ok"
cat <<EOF > xg-t-3.ok
#. a
msgid "hello world"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-t-3.ok xg-t-3.po
result=$?

rm -fr $tmpfiles

exit $result
