#! /bin/sh

# Test --foreign-user

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-test4.in.c"
cat <<EOF > xg-test4.in.c
_("extract me")
EOF

tmpfiles="$tmpfiles xg-test4.po"
: ${XGETTEXT=xgettext}
# delete POT-Creation-Date: line because the date depends on local time.
${XGETTEXT} --output - --foreign-user --no-location -k_ xg-test4.in.c \
  | sed '/\"POT-Creation-Date:.*/d' | LC_ALL=C tr -d '\r' > xg-test4.po

tmpfiles="$tmpfiles xg-test4.ok"
cat <<EOF > xg-test4.ok
# SOME DESCRIPTIVE TITLE.
# This file is put in the public domain.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "extract me"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-test4.ok xg-test4.po
result=$?

rm -fr $tmpfiles

exit $result
