#!/bin/sh

# Test Smalltalk support: --add-comments option.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-st-2.st"
cat <<\EOF > xg-st-2.st
"a"
"b" Transcript showCr:
"c" (
"d" NLS
"e" ?
"f" 'hello world' "h" ).
EOF

tmpfiles="$tmpfiles xg-st-2.tmp.po xg-st-2.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --add-comments --omit-header --no-location \
  -d xg-st-2.tmp xg-st-2.st
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < xg-st-2.tmp.po > xg-st-2.po
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-st-2.ok"
cat <<EOF > xg-st-2.ok
#. a
#. b
#. c
#. d
#. e
#. f
msgid "hello world"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-st-2.ok xg-st-2.po
result=$?

rm -fr $tmpfiles

exit $result
