#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test C support: comments meant for xgettext, and whitespace.

cat <<EOF > xg-c-2.in.c
This is a test of the xgettext functionality.
/* xgettext:no-c-format */
_("extract me")
Sometimes keywords can be spread apart
xgettext:no-c-format
_ ( "what about me" )
And even further on accasion
_
(
"hello"
)
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} -d xg-c-2.tmp -k_ --omit-header --no-location xg-c-2.in.c || exit 1
LC_ALL=C tr -d '\r' < xg-c-2.tmp.po > xg-c-2.po || exit 1

cat <<EOF > xg-c-2.ok
#, no-c-format
msgid "extract me"
msgstr ""

msgid "what about me"
msgstr ""

msgid "hello"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-c-2.ok xg-c-2.po
result=$?

exit $result
