#! /bin/sh

# Test C support: comments.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-c-5.in.cc"
cat <<EOF > xg-c-5.in.cc
main(){printf(gettext/*puke*/(/*barf*/"Hello, " "World!" "\n")); }
EOF

tmpfiles="$tmpfiles xg-c-5.tmp.po xg-c-5.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location --add-comments -d xg-c-5.tmp xg-c-5.in.cc
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < xg-c-5.tmp.po > xg-c-5.po
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-c-5.ok"
cat <<EOF > xg-c-5.ok
#. puke
#. barf
#, c-format
msgid "Hello, World!\n"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-c-5.ok xg-c-5.po
result=$?

rm -fr $tmpfiles

exit $result
