#! /bin/sh

# Test C# support: extraction of contexts.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-cs-7.cs"
cat <<\EOF > xg-cs-7.cs
Console.WriteLine(rm.GetString("help"));
Console.WriteLine(rm.GetParticularString("Help", "about"));
EOF

tmpfiles="$tmpfiles xg-cs-7.tmp.po xg-cs-7.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location -d xg-cs-7.tmp xg-cs-7.cs
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < xg-cs-7.tmp.po > xg-cs-7.po
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-cs-7.ok"
cat <<EOF > xg-cs-7.ok
msgid "help"
msgstr ""

msgctxt "Help"
msgid "about"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-cs-7.ok xg-cs-7.po
result=$?

rm -fr $tmpfiles

exit $result
