#!/bin/sh

# Test Lua support

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-lu-1.lua"
cat <<\EOF > xg-lu-1.lua
print(_("This is a test string."))
print(_('And another one.'))
print(_("Don't be afraid to extract this one."))
print(_('I don\'t bite!'))
print(_("I said: \"This is a test.\""))
print(_('He said: "You\'re right!"'))
print(_([[I like brackets.]]))
print(_([===[Brackets are awesome!]===]))
print(_(hmm["nope"]))
print({_"yep"})
print(_["nope"])
print(_("\097"))
print(_("\x3F\z  	
\x2a"))
EOF

tmpfiles="$tmpfiles xg-lu-1.tmp.po xg-lu-1.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location --add-comments=TRANSLATORS: \
  -d xg-lu-1.tmp xg-lu-1.lua
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < xg-lu-1.tmp.po > xg-lu-1.po
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-lu-1.ok"
cat <<EOF > xg-lu-1.ok
msgid "This is a test string."
msgstr ""

msgid "And another one."
msgstr ""

msgid "Don't be afraid to extract this one."
msgstr ""

msgid "I don't bite!"
msgstr ""

msgid "I said: \"This is a test.\""
msgstr ""

msgid "He said: \"You're right!\""
msgstr ""

msgid "I like brackets."
msgstr ""

msgid "Brackets are awesome!"
msgstr ""

msgid "yep"
msgstr ""

msgid "a"
msgstr ""

msgid "?*"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-lu-1.ok xg-lu-1.po
result=$?

rm -fr $tmpfiles

exit $result
