#! /bin/sh

# Test C support: extraction of 'range:' flags.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles xg-c-18.c"
cat <<\EOF > xg-c-18.c
if (days > 7 && days < 14)
  /* xgettext: range: 1..6 */
  printf (ngettext ("one week and one day", "one week and %d days",
                    days - 7),
          days - 7);
EOF

tmpfiles="$tmpfiles xg-c-18.tmp.po xg-c-18.po"
: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location -d xg-c-18.tmp xg-c-18.c
test $? = 0 || { rm -fr $tmpfiles; exit 1; }
LC_ALL=C tr -d '\r' < xg-c-18.tmp.po > xg-c-18.po
test $? = 0 || { rm -fr $tmpfiles; exit 1; }

tmpfiles="$tmpfiles xg-c-18.ok"
cat <<EOF > xg-c-18.ok
#, c-format, range: 1..6
msgid "one week and one day"
msgid_plural "one week and %d days"
msgstr[0] ""
msgstr[1] ""
EOF

: ${DIFF=diff}
${DIFF} xg-c-18.ok xg-c-18.po
result=$?

rm -fr $tmpfiles

exit $result
