#!/bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test Shell support: backslashed double-quotes inside single-quotes.

cat <<\EOF > xg-sh-3.sh
echo `gettext 'abc\"def'`
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location -d xg-sh-3.tmp xg-sh-3.sh || exit 1
LC_ALL=C tr -d '\r' < xg-sh-3.tmp.po > xg-sh-3.po || exit 1

cat <<\EOF > xg-sh-3.ok
msgid "abc\\\"def"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} xg-sh-3.ok xg-sh-3.po
result=$?

exit $result
