#!/bin/sh

#
# Creates Mac OS X bundle file. Must be run from $(builddir)/src
#
# Usage: make-bundle <bundleName.app> <rez> <top_builddir> <top_srcdir>
# 
# $Id$
#

bundle="$1"
rez="$2"
top_builddir="$3"
top_srcdir="$4"

rm -rf $bundle
mkdir -p $bundle/Contents/MacOS
mkdir -p $bundle/Contents/Resources

# executables:
cp poedit $bundle/Contents/MacOS/poedit
$rez $bundle/Contents/MacOS/poedit

if [ -n "GETTEXT_BINARIES" ] ; then
    for f in msgfmt msgmerge msgunfmt xgettext ; do
        cp -pPf $GETTEXT_BINARIES/$f $bundle/Contents/MacOS
    done
else
    echo "WARNING: not copying gettext binaries, point GETTEXT_BINARIES" >&2
    echo "         environment variable to a directory that contains them" >&2
fi

# extract (DWARF) debug information into separate dSYM files and pack them into
# an archive:
if [ -f /usr/bin/dsymutil ] ; then
    for f in $bundle/Contents/MacOS/* ; do
        dsymutil $f
    done
    tar -cjf $bundle.dSYM.tar.bz2 $bundle/Contents/MacOS/*.dSYM
    rm -rf $bundle/Contents/MacOS/*.dSYM
else
    echo "WARNING: Xcode 2.4+ is needed to extract debug information" >&2
fi

# we can strip the binaries now:
strip $bundle/Contents/MacOS/*

# metadata:
cp $top_builddir/macosx/Info.plist $bundle/Contents
cp $top_srcdir/macosx/poedit.icns $bundle/Contents/Resources

# gettext catalogs:
for i in $top_srcdir/locales/*.mo ; do
    lang=`basename $i .mo`
    mkdir -p $bundle/Contents/Resources/locale/$lang/LC_MESSAGES
    cp $i $bundle/Contents/Resources/locale/$lang/LC_MESSAGES/poedit.mo
done
for i in $top_srcdir/locales/wxwin/*.mo ; do
    lang=`basename $i .mo`
    mkdir -p $bundle/Contents/Resources/locale/$lang/LC_MESSAGES
    cp $i $bundle/Contents/Resources/locale/$lang/LC_MESSAGES/poedit-wxstd.mo
done

# icons:
iconsdir="$bundle/Contents/Resources/icons"
mkdir -p $iconsdir
cp $top_srcdir/src/icons/*.png $iconsdir
