#!/bin/sh

# Create DMG image.
#
# Arguments:
#    1. output file name
#    2. path to Poedit.app bundle
#    3. path to macosx/dmg directory with customization files

outfile="$1"
bundle="$2"
dmgfiles="$3"


imagedir="dmg-image-$$"

rm -rf $imagedir
mkdir -p $imagedir

cp -r $bundle $imagedir
ln -s /Applications $imagedir/Applications

cp $dmgfiles/DS_Store $imagedir/.DS_Store
mkdir -p $imagedir/.background
cp $dmgfiles/backgroundImage.tiff $imagedir/.background

cp $dmgfiles/VolumeIcon.icns $imagedir/.VolumeIcon.icns

hdiutil create $outfile.tmp.dmg -fs HFS+ -volname "Poedit" -format UDRW -srcfolder $imagedir

rm -rf $imagedir


mountp="`pwd`/mounted-img-$$"
hdiutil attach $outfile.tmp.dmg -mountpoint "$mountp" -nobrowse
/Developer/Tools/SetFile -a C $mountp/
hdiutil detach "$mountp"

rm -f $outfile
# can't use UDBZ (bzip2) format, because Safari may misinterpret file's content
# and rename it to .dmg.bz2, see here:
# http://unsanity.org/archives/mac_os_x/my_dmg_is_bwoken_after_download.php
hdiutil convert -format UDZO -imagekey zlib-level=9 -o $outfile $outfile.tmp.dmg
rm -f $outfile.tmp.dmg
