project_identifier: poedit
base_url: http://api.crowdin.net
base_path: .
preserve_hierarchy: false

files:
  -
    source: /locales/poedit.pot
    translation: /locales/%locale_with_underscore%.po
    languages_mapping:
      locale_with_underscore:
        af: af
        am: am
        an: an
        ar: ar
        ast: ast
        az: az
        be: be
        bg: bg
        bn: bn
        bs: bs
        ca: ca
        ckb: ckb
        co: co
        cs: cs
        da: da
        de: de
        el: el
        eo: eo
        et: et
        eu: eu
        fa: fa
        fi: fi
        fr: fr
        gl: gl
        he: he
        hi: hi
        hr: hr
        hu: hu
        hy-AM: hy
        id: id
        is: is
        it: it
        ja: ja
        ka: ka
        kab: kab
        kk: kk
        ko: ko
        ku: ku
        ky: ky
        lt: lt
        lv: lv
        mk: mk
        mn: mn
        mr: mr
        ms: ms
        nb: nb
        nl: nl
        oc: oc
        pl: pl
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sq: sq
        sr: sr
        ta: ta
        tg: tg
        th: th
        tr: tr
        ug: ug
        uk: uk
        uz: uz
        vi: vi
        wa: wa
        br-FR: br
        es-ES: es
        fur-IT: fur
        ga-IE: ga
        ne-NP: ne
        nn-NO: nn
        pa-IN: pa
        sv-SE: sv
        tt-RU: tt
        ur-PK: ur
        val-ES: ca@valencia
        zh-CN: zh_CN
        zh-TW: zh_TW
  -
    source: /locales/osx/en.lproj/InfoPlist.strings
    translation: /locales/osx/%osx_code%/InfoPlist.strings
    languages_mapping:
      osx_code:
        es-ES: es.lproj
        hy-AM: hy.lproj
        pa-IN: pa.lproj
        sv-SE: sv.lproj
  -
    source: /locales/win/windows_strings_base.rc
    translation: /locales/win/windows_strings-%language%.rc
    languages_mapping:
      language:
        az: Azeri
        en-GB: English_UK
        nb: Norwegian_Bokmal
        pt-BR: Portuguese_Brazilian
        zh-CN: Chinese_Simplified
        zh-TW: Chinese_Traditional
        sr: Serbian_Cyrillic
  -
    source: /locales/osx/en.lproj/MoveApplication.strings
    translation: /locales/osx/%osx_code%/MoveApplication.strings
    languages_mapping:
      osx_code:
        es-ES: es.lproj
        hy-AM: hy.lproj
        pa-IN: pa.lproj
        sv-SE: sv.lproj

