_("About poEdit")
_("version 1.1.7")
_("OK")
_("Edit comment")
_("Comment:")
_("OK")
_("Cancel")
_("Clear")
_("Clear the comment")
_("Edit the file in text editor")
_("Find...")
_("String to find:")
_("Case sensitive")
_("Find in original strings")
_("Find in translations")
_("Cancel")
_("< Previous")
_("Next >")
_("Create new translations project")
_("Edit the project")
_("Delete the project")
_("Update all catalogs in the project")
_("Edit project")
_("Project name:")
_("Browse")
_("Add directory to the list")
_("OK")
_("Cancel")
_("&File")
_("Catalogs manager")
_("&New catalog...")
_("&Open")
_("&Save")
_("Save &as...")
_("Preferences...")
_("&Close")
_("&Edit")
_("Copy original to translation field")
_("&Show references")
_("Find...")
_("Translation is &fuzzy")
_("Edit comment")
_("&Catalog")
_("&Update catalog")
_("&Settings...")
_("&View")
_("&Fullscreen view")
_("Display &quotes")
_("Display &line numbers")
_("Contents...")
_("&About...")
_("&Help")
_("Preferences")
_("Identity")
_("Your name:")
_("Your e-mail address:")
_("Behavior")
_("Automatically compile .mo file on save")
_("Show summary after catalog update")
_("Open catalogs manager on poEdit startup")
_("Always change focus to text input field")
_("Never let the list of strings take focus. If enabled, you must use Ctrl-arrows for keyboard navigation but you can also type text immediately, without having to press Tab to change focus.")
_("Shaded translations list")
_("CR/LF conversion")
_("Line endings format:")
_("Don't change format of existing catalogs")
_("External editor")
_("Editor executable:")
_("(%f will be substituted with filename, %l with line number)")
_("Open source files in editor, not in file viewer")
_("Editor")
_("Database")
_("Path to DB:")
_("Browse")
_("Add")
_("Pick language from the list of known languages")
_("Generate database")
_("Regenerate translation memory from catalogs in paths listed above.")
_("Configuration")
_("Max. # of missing words:")
_("Max. difference in sentence length:")
_("Automatically translate when updating catalog")
_("Translation Memory")
_("Source code parsers:")
_("New")
_("Edit")
_("Delete")
_("Parsers")
_("OK")
_("Cancel")
_("Parser setup")
_("Language:")
_("Language:")
_("List of extensions separated by semicolons (e.g. *.cpp, *.h):")
_("Invocation:")
_("Parser command:")
_("This is the command used to launch the parser.\n%o expands to the name of output file, %K to list\nof keywords, %F to list of input files (see bellow).")
_("An item in keywords list:")
_("This will be attached to the command line once\nfor each keyword. %k expands to the keyword.")
_("An item in input files list:")
_("This will be attached to the command line once\nfor each input file. %f expands to the filename.")
_("OK")
_("Cancel")
_("Browse")
_("Add path to the list of directories where catalogs lie.")
_("Proceed")
_("Cancel")
_("Generate TM database")
_("Updating catalog...")
_("Merging differences...")
_("Cancel")
_("Settings")
_("Project name and version:")
_("Team:")
_("Team's email address:")
_("Language:")
_("Charset:")
_("Project info")
_("Base path:")
_("Paths")
_("Use these keywords (function names) to recognize translatable strings\nin source files, in addition to default ones.")
_("Keywords")
_("OK")
_("Cancel")
_("Update summary")
_("These strings were found in the sources but were not in the catalog.\npoEdit will add them to the catalog now.")
_("New strings")
_("These strings are no longer in the sources.\npoEdit will remove them from the catalog now.")
_("Obsolete strings")
_("(0 new, 0 obsolete)")
_("OK")
_("Undo")
_("Open catalog")
_("Save catalog")
_("Update catalog - synchronize it with sources")
_("Display quotes around the string?")
_("Toggled if selected string has fuzzy translation")
_("Edit comment")
_("Fullscreen view")
_("Help")
