name: poedit
version: git
summary: Gettext translations editor for OS X, Windows and Unix.
description: |
  This program is a GUI frontend to GNU Gettext utilities and a catalogs
  editor/source code parser. It helps with translating applications into
  other languages.

  By default Poedit can only open files under your home directory, to
  allow Poedit access files under /media run the following command in
  terminal as superuser:

    # snap connect poedit:removable-media

grade: devel
confinement: strict
icon: poedit.png

apps:
  poedit:
    command: desktop-launch poedit
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - removable-media
      - x11
    desktop: share/applications/poedit.desktop

parts:
  poedit:
    source: https://github.com/vslavik/poedit.git
    source-type: git
    source-depth: 80
    override-pull: |
      # There's no way we pull all the submodules down, we do this manually
      git clone --depth=80 https://github.com/vslavik/poedit.git .
      git submodule init deps/json
      git submodule update --depth=200

    build-packages:
      # Boost libraries provided by Ubuntu 16.04 are too old, using
      # installation from `boostlib` part instead
      #- libboost-dev
      #- libboost-iostreams-dev
      #- libboost-regex-dev
      #- libboost-system-dev
      #- libboost-thread-dev

      # wxWidgets library provided by Ubuntu 16.04 is too old, using
      # installation from `wxwidgets` part instead
      #- libwxgtk3.0-dev

      # "JSON for Modern C++" is only provided by Ubuntu >= 17.10,
      # using embedded submodule's version instead
      #- nlohmann-json-dev

      # GCC(`g++` to be specific) provided by Ubuntu 16.04 is too
      # old for the embedded submodule "JSON for Modern C++", use
      # installation from `gcc-6` part instead.
      #- gcc
      #- g++

      - asciidoc
      - automake
      - gettext
      - libcld2-dev
      - libcpprest-dev
      - libgtkspell3-3-dev
      - libicu-dev
      - libjpeg-dev
      - liblucene++-dev
      - libnotify-dev
      - libsecret-1-dev
      - libtiff5-dev
      - pkg-config
      - xsltproc
      - xmlto
      - zlib1g-dev

    plugin: autotools
    configflags:
      - --with-wx-prefix=$SNAPCRAFT_PART_INSTALL/../../wxwidgets/install
      - --with-boost=$SNAPCRAFT_PART_INSTALL/../../boostlib/install

      - CC=gcc-6
      - CXX=g++-6
      # wxWidgets DSO linking option bug due to linker behavior change,
      # consider upgrading the submodule
      - LDFLAGS=-Wl,--copy-dt-needed-entries
    install-via: prefix
    override-build: |
      ./bootstrap
      snapcraftctl build

      sed -i 's|^Icon=.*|Icon=\${SNAP}/meta/gui/icon.png|' \
        ${SNAPCRAFT_PART_INSTALL}/share/applications/poedit.desktop

    stage-packages:
      # For addr2line, required by wxWidgets error dialog
      - binutils

      # Called by Poedit
      - gettext

      - libboost-iostreams1.58.0
      - libboost-regex1.58.0
      - libboost-thread1.58.0
      - libcld2-0
      - libcpprest2.8
      - libenchant1c2a
      - libgtkspell3-3-0
      - libice6
      - liblucene++0v5
      - libsecret-1-0
      - libsm6
      - libxxf86vm1

    filesets:
      executables:
        - bin/*
      files-in-stage-packages:
        - usr/*
      freedesktop-desktop-entries:
        - share/applications/*
      icons:
        - share/icons/*
      localizations:
        - share/locale/*
      manpages:
        - share/man/*
      pixmaps:
        - share/pixmaps/*
      resources:
        - share/poedit/*

    stage:
      - $executables
      - $files-in-stage-packages
      - $freedesktop-desktop-entries
      - $manpages
      - $localizations
      - $pixmaps
      - $resources

    prime:
      - $executables
      - $files-in-stage-packages
      - $freedesktop-desktop-entries
      - $manpages
      - $localizations
      - $pixmaps
      - $resources

    after:
      - boostlib
      - desktop-gtk3
      - gcc-6
      - wxwidgets

  boostlib:
    source: https://github.com/vslavik/poedit.git
    source-type: git
    source-depth: 1
    source-subdir: deps/boost
    override-pull: |
      # NOTE: Overrided until submodule fetching is optional
      #snapcraftctl pull

      git clone --depth=1 https://github.com/vslavik/poedit.git .

    build-packages:
      # OPTIONAL: Use gcc installation from `gcc-6` part instead
      #- gcc
      #- g++
      - libbz2-dev
      - libicu-dev

    plugin: dump
    override-build: |
      cd deps/boost
      echo 'using gcc : : g++-6 ;' >user-config.jam
      ./bootstrap.sh \
        --prefix="${SNAPCRAFT_PART_INSTALL}" \
        --with-libraries=iostreams,regex,system,thread \
        --with-icu=/usr
      ./b2 install \
        -j $(nproc) \
        --build-type=minimal \
        threading=multi \
        link=static

    filesets:
      headers:
        - include/*
      static-libs:
        - lib/*.a

    stage:
      - -*

    prime:
      - -*

    after:
      - gcc-6

  wxwidgets:
    source: https://github.com/vslavik/wxWidgets.git
    source-type: git
    source-depth: 1

    build-packages:
      # OPTIONAL: Use gcc installation from `gcc-6` part instead
      #- gcc
      #- g++

      - gettext
      - libcairo2-dev
      - libexpat1-dev

      # Not used by Poedit
      #- libgl1-mesa-dev
      #- libglu1-mesa-dev
      #- libgstreamer1.0-dev
      #- libgstreamer-plugins-base1.0-dev

      - libgtk-3-dev
      - libjpeg-dev
      - libnotify-dev
      - libpng-dev
      - libsecret-1-dev

      - libtiff5-dev

      # Not used by Poedit
      #- libwebkit2gtk-4.0-dev

      - libxtst-dev

      - zlib1g-dev

    plugin: autotools
    configflags:
      - --disable-shared
      - --disable-sound
      - --with-gtk=3
      - --without-opengl
      - --without-sdl
      # OPTIONAL: Use gcc installation from `gcc-6` part instead
      - CC=gcc-6
      - CXX=g++-6
    install-via: prefix

    filesets:
      headers:
        - include/*
      static-libs:
        - lib/*.a

    stage:
      - -*

    prime:
      - -*

    after:
      - gcc-6

  gcc-6:
    plugin: nil
    override-build: |
      # Install newer GCC from Toolchain test builds PPA
      sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
      sudo apt update
      sudo apt install gcc-6 g++-6
