
#include <wx/wxprec.h>

#include "iso639.h"

LanguageStruct isoLanguages[] =
{
    {_T("aa"), _T("Afar")},
    {_T("ab"), _T("Abkhazian")},
    {_T("ae"), _T("Avestan")},
    {_T("af"), _T("Afrikaans")},
    {_T("am"), _T("Amharic")},
    {_T("ar"), _T("Arabic")},
    {_T("as"), _T("Assamese")},
    {_T("ay"), _T("Aymara")},
    {_T("az"), _T("Azerbaijani")},

    {_T("ba"), _T("Bashkir")},
    {_T("be"), _T("Byelorussian")},
    {_T("bg"), _T("Bulgarian")},
    {_T("bh"), _T("Bihari")},
    {_T("bi"), _T("Bislama")},
    {_T("bn"), _T("Bengali")},
    {_T("bo"), _T("Tibetan")},
    {_T("br"), _T("Breton")},
    {_T("bs"), _T("Bosnian")},

    {_T("ca"), _T("Catalan")},
    {_T("ce"), _T("Chechen")},
    {_T("ch"), _T("Chamorro")},
    {_T("co"), _T("Corsican")},
    {_T("cs"), _T("Czech")},
    {_T("cu"), _T("Church Slavic")},
    {_T("cv"), _T("Chuvash")},
    {_T("cy"), _T("Welsh")},

    {_T("da"), _T("Danish")},
    {_T("de"), _T("German")},
    {_T("dz"), _T("Dzongkha")},

    {_T("el"), _T("Greek")},
    {_T("en"), _T("English")},
    {_T("eo"), _T("Esperanto")},
    {_T("es"), _T("Spanish")},
    {_T("et"), _T("Estonian")},
    {_T("eu"), _T("Basque")},

    {_T("fa"), _T("Persian")},
    {_T("fi"), _T("Finnish")},
    {_T("fj"), _T("Fijian")},
    {_T("fo"), _T("Faroese")},
    {_T("fr"), _T("French")},
    {_T("fy"), _T("Frisian")},

    {_T("ga"), _T("Irish")},
    {_T("gd"), _T("Gaelic")},
    {_T("gl"), _T("Gallegan")},
    {_T("gn"), _T("Guarani")},
    {_T("gu"), _T("Gujarati")},

    {_T("ha"), _T("Hausa")},
    {_T("he"), _T("Hebrew")},
    {_T("hi"), _T("Hindi")},
    {_T("ho"), _T("Hiri Motu")},
    {_T("hr"), _T("Croatian")},
    {_T("hu"), _T("Hungarian")},
    {_T("hy"), _T("Armenian")},
    {_T("hz"), _T("Herero")},

    {_T("ia"), _T("Interlingua")},
    {_T("id"), _T("Indonesian")},
    {_T("ie"), _T("Interlingue")},
    {_T("ik"), _T("Inupiaq")},
    {_T("is"), _T("Icelandic")},
    {_T("it"), _T("Italian")},
    {_T("iu"), _T("Inuktitut")},

    {_T("ja"), _T("Japanese")},
    {_T("jw"), _T("Javanese")},

    {_T("ka"), _T("Georgian")},
    {_T("ki"), _T("Kikuyu")},
    {_T("kj"), _T("Kuanyama")},
    {_T("kk"), _T("Kazakh")},
    {_T("kl"), _T("Kalaallisut")},
    {_T("km"), _T("Khmer")},
    {_T("kn"), _T("Kannada")},
    {_T("ko"), _T("Korean")},
    {_T("ks"), _T("Kashmiri")},
    {_T("ku"), _T("Kurdish")},
    {_T("kv"), _T("Komi")},
    {_T("kw"), _T("Cornish")},
    {_T("ky"), _T("Kirghiz")},

    {_T("la"), _T("Latin")},
    {_T("lb"), _T("Letzeburgesch")},
    {_T("ln"), _T("Lingala")},
    {_T("lo"), _T("Lao")},
    {_T("lt"), _T("Lithuanian")},
    {_T("lv"), _T("Latvian")},

    {_T("mg"), _T("Malagasy")},
    {_T("mh"), _T("Marshall")},
    {_T("mi"), _T("Maori")},
    {_T("mk"), _T("Macedonian")},
    {_T("ml"), _T("Malayalam")},
    {_T("mn"), _T("Mongolian")},
    {_T("mo"), _T("Moldavian")},
    {_T("mr"), _T("Marathi")},
    {_T("ms"), _T("Malay")},
    {_T("mt"), _T("Maltese")},
    {_T("my"), _T("Burmese")},

    {_T("na"), _T("Nauru")},
    {_T("nb"), _T("Norwegian Bokmål")},
    {_T("ne"), _T("Nepali")},
    {_T("ng"), _T("Ndonga")},
    {_T("nl"), _T("Dutch")},
    {_T("nn"), _T("Norwegian Nynorsk")},
    {_T("no"), _T("Norwegian")},
    {_T("nr"), _T("Ndebele, South")},
    {_T("nv"), _T("Navajo")},
    {_T("ny"), _T("Chichewa; Nyanja")},

    {_T("oc"), _T("Occitan")},
    {_T("om"), _T("(Afan) Oromo")},
    {_T("or"), _T("Oriya")},
    {_T("os"), _T("Ossetian; Ossetic")},

    {_T("pa"), _T("Panjabi")},
    {_T("pi"), _T("Pali")},
    {_T("pl"), _T("Polish")},
    {_T("ps"), _T("Pashto, Pushto")},
    {_T("pt"), _T("Portuguese")},

    {_T("qu"), _T("Quechua")},

    {_T("rm"), _T("Rhaeto-Romance")},
    {_T("rn"), _T("Rundi")},
    {_T("ro"), _T("Romanian")},
    {_T("ru"), _T("Russian")},
    {_T("rw"), _T("Kinyarwanda")},

    {_T("sa"), _T("Sanskrit")},
    {_T("sc"), _T("Sardinian")},
    {_T("sd"), _T("Sindhi")},
    {_T("se"), _T("Northern Sami")},
    {_T("sg"), _T("Sangro")},
    {_T("sh"), _T("Serbo-Croatian")},
    {_T("si"), _T("Sinhalese")},
    {_T("sk"), _T("Slovak")},
    {_T("sl"), _T("Slovenian")},
    {_T("sm"), _T("Samoan")},
    {_T("sn"), _T("Shona")},
    {_T("so"), _T("Somali")},
    {_T("sq"), _T("Albanian")},
    {_T("sr"), _T("Serbian")},
    {_T("ss"), _T("Siswati")},
    {_T("st"), _T("Sesotho")},
    {_T("su"), _T("Sundanese")},
    {_T("sv"), _T("Swedish")},
    {_T("sw"), _T("Swahili")},

    {_T("ta"), _T("Tamil")},
    {_T("te"), _T("Telugu")},
    {_T("tg"), _T("Tajik")},
    {_T("th"), _T("Thai")},
    {_T("ti"), _T("Tigrinya")},
    {_T("tk"), _T("Turkmen")},
    {_T("tl"), _T("Tagalog")},
    {_T("tn"), _T("Setswana")},
    {_T("to"), _T("Tonga")},
    {_T("tr"), _T("Turkish")},
    {_T("ts"), _T("Tsonga")},
    {_T("tt"), _T("Tatar")},
    {_T("tw"), _T("Twi")},
    {_T("ty"), _T("Tahitian")},

    {_T("ug"), _T("Uighur")},
    {_T("uk"), _T("Ukrainian")},
    {_T("ur"), _T("Urdu")},
    {_T("uz"), _T("Uzbek")},

    {_T("vi"), _T("Vietnamese")},
    {_T("vo"), _T("Volapuk")},

    {_T("wo"), _T("Wolof")},

    {_T("xh"), _T("Xhosa")},

    {_T("yi"), _T("Yiddish")},
    {_T("yo"), _T("Yoruba")},

    {_T("za"), _T("Zhuang")},
    {_T("zh"), _T("Chinese")},
    {_T("zu"), _T("Zulu")},
    
    {NULL, NULL}
};
