'\" t
.\"     Title: poedit
.\"    Author: Vaclav Slavik <vaclav@slavik.io>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/11/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "POEDIT" "1" "06/11/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
poedit \- gettext catalogs editor
.SH "SYNOPSIS"
.HP \w'\fBpoedit\fR\ 'u
\fBpoedit\fR [\fB\-h\fR] [\fB\-\-verbose\fR] [\fIFILE\fR...]
.SH "DESCRIPTION"
.sp
Poedit is GUI editor for GNU gettext translation files\&.
.sp
When launched with one or more files as argument, it loads and opens them for editing\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display usage information and exit\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
Print verbose logging information\&.
.RE
.SH "AUTHOR"
.sp
Written by Vaclav Slavik <\m[blue]\fBvaclav@slavik\&.io\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "RESOURCES"
.sp
Web site: \m[blue]\fBhttps://poedit\&.net/\fR\m[]
.SH "COPYRIGHT"
.sp
Copyright (C) 2008\-2019 Vaclav Slavik\&.
.sp
Free use of this software is granted under the terms of the MIT license\&.
.SH "AUTHOR"
.PP
\fBVaclav Slavik\fR <\&vaclav@slavik\&.io\&>
.RS 4
Author.
.RE
.SH "NOTES"
.IP " 1." 4
vaclav@slavik.io
.RS 4
\%mailto:vaclav@slavik.io
.RE
