// Code generated with scripts/extract-plural-forms.py begins here

{ "af"   , "nplurals=2; plural=(n != 1);" },
{ "ak"   , "nplurals=2; plural=(n > 1);" },
{ "am"   , "nplurals=2; plural=(n==0 || n==1);" },
{ "ar"   , "nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5);" },
{ "ars"  , "nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5);" },
{ "as"   , "nplurals=2; plural=(n==0 || n==1);" },
{ "asa"  , "nplurals=2; plural=(n != 1);" },
{ "ast"  , "nplurals=2; plural=(n != 1);" },
{ "az"   , "nplurals=2; plural=(n != 1);" },
{ "be"   , "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);" },
{ "bem"  , "nplurals=2; plural=(n != 1);" },
{ "bez"  , "nplurals=2; plural=(n != 1);" },
{ "bg"   , "nplurals=2; plural=(n != 1);" },
{ "bh"   , "nplurals=2; plural=(n > 1);" },
{ "bm"   , "nplurals=1; plural=0;" },
{ "bn"   , "nplurals=2; plural=(n==0 || n==1);" },
{ "bo"   , "nplurals=1; plural=0;" },
{ "br"   , "nplurals=5; plural=(n%10==1 && n%100!=11 && n%100!=71 && n%100!=91 ? 0 : n%10==2 && n%100!=12 && n%100!=72 && n%100!=92 ? 1 : ((n%10>=3 && n%10<=4) || n%10==9) && (n%100<10 || n%100>19) && (n%100<70 || n%100>79) && (n%100<90 || n%100>99) ? 2 : n!=0 && n%1000000==0 ? 3 : 4);" },
{ "brx"  , "nplurals=2; plural=(n != 1);" },
{ "bs"   , "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);" },
{ "ca"   , "nplurals=2; plural=(n != 1);" },
{ "ce"   , "nplurals=2; plural=(n != 1);" },
{ "cgg"  , "nplurals=2; plural=(n != 1);" },
{ "chr"  , "nplurals=2; plural=(n != 1);" },
{ "ckb"  , "nplurals=2; plural=(n != 1);" },
{ "cs"   , "nplurals=3; plural=(n==1 ? 0 : n>=2 && n<=4 ? 1 : 2);" },
{ "cy"   , "nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n==3 ? 3 : n==6 ? 4 : 5);" },
{ "da"   , "nplurals=2; plural=(n != 1);" },
{ "de"   , "nplurals=2; plural=(n != 1);" },
{ "dsb"  , "nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100>=3 && n%100<=4 ? 2 : 3);" },
{ "dv"   , "nplurals=2; plural=(n != 1);" },
{ "dz"   , "nplurals=1; plural=0;" },
{ "ee"   , "nplurals=2; plural=(n != 1);" },
{ "el"   , "nplurals=2; plural=(n != 1);" },
{ "en"   , "nplurals=2; plural=(n != 1);" },
{ "eo"   , "nplurals=2; plural=(n != 1);" },
{ "es"   , "nplurals=2; plural=(n != 1);" },
{ "et"   , "nplurals=2; plural=(n != 1);" },
{ "eu"   , "nplurals=2; plural=(n != 1);" },
{ "fa"   , "nplurals=2; plural=(n==0 || n==1);" },
{ "ff"   , "nplurals=2; plural=(n > 1);" },
{ "fi"   , "nplurals=2; plural=(n != 1);" },
{ "fil"  , "nplurals=2; plural=(n==1 || n==2 || n==3 || (n%10!=4 && n%10!=6 && n%10!=9));" },
{ "fo"   , "nplurals=2; plural=(n != 1);" },
{ "fr"   , "nplurals=2; plural=(n > 1);" },
{ "fur"  , "nplurals=2; plural=(n != 1);" },
{ "fy"   , "nplurals=2; plural=(n != 1);" },
{ "ga"   , "nplurals=5; plural=(n==1 ? 0 : n==2 ? 1 : n>=3 && n<=6 ? 2 : n>=7 && n<=10 ? 3 : 4);" },
{ "gd"   , "nplurals=4; plural=(n==1 || n==11 ? 0 : n==2 || n==12 ? 1 : (n>=3 && n<=10) || (n>=13 && n<=19) ? 2 : 3);" },
{ "gl"   , "nplurals=2; plural=(n != 1);" },
{ "gsw"  , "nplurals=2; plural=(n != 1);" },
{ "gu"   , "nplurals=2; plural=(n==0 || n==1);" },
{ "guw"  , "nplurals=2; plural=(n > 1);" },
{ "gv"   , "nplurals=4; plural=(n%10==1 ? 0 : n%10==2 ? 1 : n%100==0 || n%100==20 || n%100==40 || n%100==60 || n%100==80 ? 2 : 3);" },
{ "ha"   , "nplurals=2; plural=(n != 1);" },
{ "haw"  , "nplurals=2; plural=(n != 1);" },
{ "he"   , "nplurals=4; plural=(n==1 ? 0 : n==2 ? 1 : n>10 && n%10==0 ? 2 : 3);" },
{ "hi"   , "nplurals=2; plural=(n==0 || n==1);" },
{ "hr"   , "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);" },
{ "hsb"  , "nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100>=3 && n%100<=4 ? 2 : 3);" },
{ "hu"   , "nplurals=2; plural=(n != 1);" },
{ "hy"   , "nplurals=2; plural=(n > 1);" },
{ "id"   , "nplurals=1; plural=0;" },
{ "ig"   , "nplurals=1; plural=0;" },
{ "ii"   , "nplurals=1; plural=0;" },
{ "in"   , "nplurals=1; plural=0;" },
{ "io"   , "nplurals=2; plural=(n != 1);" },
{ "is"   , "nplurals=2; plural=(n%10==1 && n%100!=11);" },
{ "it"   , "nplurals=2; plural=(n != 1);" },
{ "iu"   , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "iw"   , "nplurals=4; plural=(n==1 ? 0 : n==2 ? 1 : n>10 && n%10==0 ? 2 : 3);" },
{ "ja"   , "nplurals=1; plural=0;" },
{ "jbo"  , "nplurals=1; plural=0;" },
{ "jgo"  , "nplurals=2; plural=(n != 1);" },
{ "ji"   , "nplurals=2; plural=(n != 1);" },
{ "jmc"  , "nplurals=2; plural=(n != 1);" },
{ "jv"   , "nplurals=1; plural=0;" },
{ "jw"   , "nplurals=1; plural=0;" },
{ "ka"   , "nplurals=2; plural=(n != 1);" },
{ "kab"  , "nplurals=2; plural=(n > 1);" },
{ "kaj"  , "nplurals=2; plural=(n != 1);" },
{ "kcg"  , "nplurals=2; plural=(n != 1);" },
{ "kde"  , "nplurals=1; plural=0;" },
{ "kea"  , "nplurals=1; plural=0;" },
{ "kk"   , "nplurals=2; plural=(n != 1);" },
{ "kkj"  , "nplurals=2; plural=(n != 1);" },
{ "kl"   , "nplurals=2; plural=(n != 1);" },
{ "km"   , "nplurals=1; plural=0;" },
{ "kn"   , "nplurals=2; plural=(n==0 || n==1);" },
{ "ko"   , "nplurals=1; plural=0;" },
{ "ks"   , "nplurals=2; plural=(n != 1);" },
{ "ksb"  , "nplurals=2; plural=(n != 1);" },
{ "ksh"  , "nplurals=3; plural=(n==0 ? 0 : n==1 ? 1 : 2);" },
{ "ku"   , "nplurals=2; plural=(n != 1);" },
{ "kw"   , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "ky"   , "nplurals=2; plural=(n != 1);" },
{ "lag"  , "nplurals=3; plural=(n==0 ? 0 : (n==0 || n==1) && n!=0 ? 1 : 2);" },
{ "lb"   , "nplurals=2; plural=(n != 1);" },
{ "lg"   , "nplurals=2; plural=(n != 1);" },
{ "lkt"  , "nplurals=1; plural=0;" },
{ "ln"   , "nplurals=2; plural=(n > 1);" },
{ "lo"   , "nplurals=1; plural=0;" },
{ "lt"   , "nplurals=3; plural=(n%10==1 && (n%100<11 || n%100>19) ? 0 : n%10>=2 && n%10<=9 && (n%100<11 || n%100>19) ? 1 : 2);" },
{ "lv"   , "nplurals=3; plural=(n%10==0 || (n%100>=11 && n%100<=19) ? 0 : n%10==1 && n%100!=11 ? 1 : 2);" },
{ "mas"  , "nplurals=2; plural=(n != 1);" },
{ "mg"   , "nplurals=2; plural=(n > 1);" },
{ "mgo"  , "nplurals=2; plural=(n != 1);" },
{ "mk"   , "nplurals=2; plural=(n%10==1 && n%100!=11);" },
{ "ml"   , "nplurals=2; plural=(n != 1);" },
{ "mn"   , "nplurals=2; plural=(n != 1);" },
{ "mo"   , "nplurals=3; plural=(n==1 ? 0 : n==0 || (n!=1 && n%100>=1 && n%100<=19) ? 1 : 2);" },
{ "mr"   , "nplurals=2; plural=(n==0 || n==1);" },
{ "ms"   , "nplurals=1; plural=0;" },
{ "mt"   , "nplurals=4; plural=(n==1 ? 0 : n==0 || (n%100>=2 && n%100<=10) ? 1 : n%100>=11 && n%100<=19 ? 2 : 3);" },
{ "my"   , "nplurals=1; plural=0;" },
{ "nah"  , "nplurals=2; plural=(n != 1);" },
{ "naq"  , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "nb"   , "nplurals=2; plural=(n != 1);" },
{ "nd"   , "nplurals=2; plural=(n != 1);" },
{ "ne"   , "nplurals=2; plural=(n != 1);" },
{ "nl"   , "nplurals=2; plural=(n != 1);" },
{ "nn"   , "nplurals=2; plural=(n != 1);" },
{ "nnh"  , "nplurals=2; plural=(n != 1);" },
{ "no"   , "nplurals=2; plural=(n != 1);" },
{ "nqo"  , "nplurals=1; plural=0;" },
{ "nr"   , "nplurals=2; plural=(n != 1);" },
{ "nso"  , "nplurals=2; plural=(n > 1);" },
{ "ny"   , "nplurals=2; plural=(n != 1);" },
{ "nyn"  , "nplurals=2; plural=(n != 1);" },
{ "om"   , "nplurals=2; plural=(n != 1);" },
{ "or"   , "nplurals=2; plural=(n != 1);" },
{ "os"   , "nplurals=2; plural=(n != 1);" },
{ "pa"   , "nplurals=2; plural=(n > 1);" },
{ "pap"  , "nplurals=2; plural=(n != 1);" },
{ "pl"   , "nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);" },
{ "prg"  , "nplurals=3; plural=(n%10==0 || (n%100>=11 && n%100<=19) ? 0 : n%10==1 && n%100!=11 ? 1 : 2);" },
{ "ps"   , "nplurals=2; plural=(n != 1);" },
{ "pt"   , "nplurals=2; plural=(n > 1);" },
{ "pt_PT", "nplurals=2; plural=(n != 1);" },
{ "rm"   , "nplurals=2; plural=(n != 1);" },
{ "ro"   , "nplurals=3; plural=(n==1 ? 0 : n==0 || (n!=1 && n%100>=1 && n%100<=19) ? 1 : 2);" },
{ "rof"  , "nplurals=2; plural=(n != 1);" },
{ "root" , "nplurals=1; plural=0;" },
{ "ru"   , "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);" },
{ "rwk"  , "nplurals=2; plural=(n != 1);" },
{ "sah"  , "nplurals=1; plural=0;" },
{ "saq"  , "nplurals=2; plural=(n != 1);" },
{ "scn"  , "nplurals=2; plural=(n != 1);" },
{ "sd"   , "nplurals=2; plural=(n != 1);" },
{ "sdh"  , "nplurals=2; plural=(n != 1);" },
{ "se"   , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "seh"  , "nplurals=2; plural=(n != 1);" },
{ "ses"  , "nplurals=1; plural=0;" },
{ "sg"   , "nplurals=1; plural=0;" },
{ "sh"   , "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);" },
{ "shi"  , "nplurals=3; plural=(n==0 || n==1 ? 0 : n>=2 && n<=10 ? 1 : 2);" },
{ "si"   , "nplurals=2; plural=(n > 1);" },
{ "sk"   , "nplurals=3; plural=(n==1 ? 0 : n>=2 && n<=4 ? 1 : 2);" },
{ "sl"   , "nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100>=3 && n%100<=4 ? 2 : 3);" },
{ "sma"  , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "smi"  , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "smj"  , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "smn"  , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "sms"  , "nplurals=3; plural=(n==1 ? 0 : n==2 ? 1 : 2);" },
{ "sn"   , "nplurals=2; plural=(n != 1);" },
{ "so"   , "nplurals=2; plural=(n != 1);" },
{ "sq"   , "nplurals=2; plural=(n != 1);" },
{ "sr"   , "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);" },
{ "ss"   , "nplurals=2; plural=(n != 1);" },
{ "ssy"  , "nplurals=2; plural=(n != 1);" },
{ "st"   , "nplurals=2; plural=(n != 1);" },
{ "sv"   , "nplurals=2; plural=(n != 1);" },
{ "sw"   , "nplurals=2; plural=(n != 1);" },
{ "syr"  , "nplurals=2; plural=(n != 1);" },
{ "ta"   , "nplurals=2; plural=(n != 1);" },
{ "te"   , "nplurals=2; plural=(n != 1);" },
{ "teo"  , "nplurals=2; plural=(n != 1);" },
{ "th"   , "nplurals=1; plural=0;" },
{ "ti"   , "nplurals=2; plural=(n > 1);" },
{ "tig"  , "nplurals=2; plural=(n != 1);" },
{ "tk"   , "nplurals=2; plural=(n != 1);" },
{ "tl"   , "nplurals=2; plural=(n==1 || n==2 || n==3 || (n%10!=4 && n%10!=6 && n%10!=9));" },
{ "tn"   , "nplurals=2; plural=(n != 1);" },
{ "to"   , "nplurals=1; plural=0;" },
{ "tr"   , "nplurals=2; plural=(n != 1);" },
{ "ts"   , "nplurals=2; plural=(n != 1);" },
{ "tzm"  , "nplurals=2; plural=(n<=1 || (n>=11 && n<=99));" },
{ "ug"   , "nplurals=2; plural=(n != 1);" },
{ "uk"   , "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);" },
{ "ur"   , "nplurals=2; plural=(n != 1);" },
{ "uz"   , "nplurals=2; plural=(n != 1);" },
{ "ve"   , "nplurals=2; plural=(n != 1);" },
{ "vi"   , "nplurals=1; plural=0;" },
{ "vo"   , "nplurals=2; plural=(n != 1);" },
{ "vun"  , "nplurals=2; plural=(n != 1);" },
{ "wa"   , "nplurals=2; plural=(n > 1);" },
{ "wae"  , "nplurals=2; plural=(n != 1);" },
{ "wo"   , "nplurals=1; plural=0;" },
{ "xh"   , "nplurals=2; plural=(n != 1);" },
{ "xog"  , "nplurals=2; plural=(n != 1);" },
{ "yi"   , "nplurals=2; plural=(n != 1);" },
{ "yo"   , "nplurals=1; plural=0;" },
{ "yue"  , "nplurals=1; plural=0;" },
{ "zh"   , "nplurals=1; plural=0;" },
{ "zu"   , "nplurals=2; plural=(n==0 || n==1);" },

// Code generated with scripts/extract-plural-forms.py ends here



