name: poedit
version: 2.2.4
summary: Simple translation editor
description: >
  Translation editor for gettext (PO files) and XLIFF.
  It helps with translating applications or WordPress themes and plugins into
  other languages, as well as with developing localizable applications.

  By default Poedit snap can only open files under your home directory, to
  allow Poedit access files under /media you must connect this snap to the
  `removable-media` interface by running the following command:

    $ sudo snap connect poedit:removable-media

  For Poedit to save credential data for Crowdin integration you must
  connect this snap to the `password-manager-service` interface:

    $ snap connect poedit:password-manager-service

base: core18
grade: stable
confinement: strict
icon: artwork/linux/appicon/256x256/apps/net.poedit.Poedit.png

layout:
  /usr/share/aspell:
    symlink: $SNAP/usr/share/aspell
  /usr/share/hunspell:
    symlink: $SNAP/usr/share/hunspell
  /usr/share/myspell:
    symlink: $SNAP/usr/share/myspell
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/enchant:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/enchant

apps:
  poedit:
    command: bin/poedit
    desktop: share/applications/net.poedit.Poedit.desktop
    extensions: [gnome-3-28]

  poedit-uri-handler:
    command: bin/poedit
    desktop: share/applications/net.poedit.PoeditURI.desktop
    extensions: [gnome-3-28]

plugs:
  # File access
  home:
  removable-media:

  # Crowdin access
  network:

  # Secret Service access
  password-manager-service:

  # Suggestions from snappy-debug
  gsettings:
  mount-observe:

parts:
  poedit:
    after:
      - wxwidgets

    source: .

    build-packages:
      # wxWidgets library provided by Ubuntu 16.04 is too old, using
      # installation from `wxwidgets` part instead
      #- libwxgtk3.0-dev

      # "JSON for Modern C++" is only provided by Ubuntu >= 17.10,
      # using embedded submodule's version instead
      #- nlohmann-json-dev

      - automake
      - gettext
      - libboost-all-dev
      - libcld2-dev
      - libcpprest-dev
      - libgtkspell3-3-dev
      - libicu-dev
      - libjpeg-dev
      - liblucene++-dev
      - libnotify-dev
      - libsecret-1-dev
      - libtiff5-dev
      - pkg-config
      - zlib1g-dev

    plugin: autotools
    override-build: |
      set -eu

      ./bootstrap
      ./configure \
        --with-wx-prefix="$SNAPCRAFT_STAGE" \
        CPPFLAGS="-I${SNAPCRAFT_STAGE}/include -I${SNAPCRAFT_PART_INSTALL}/../build/deps/json/src" \
        LDFLAGS="-Wl,--copy-dt-needed-entries -L${SNAPCRAFT_STAGE}/lib" \
        PKG_CONFIG_PATH="${SNAPCRAFT_STAGE}"/lib/pkgconfig
      make -j2
      make prefix="${SNAPCRAFT_PART_INSTALL}" install-strip

      # Fix-up application icon lookup
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/meta/gui/
      cp artwork/linux/appicon/256x256/apps/net.poedit.Poedit.png ${SNAPCRAFT_PART_INSTALL}/meta/gui/icon.png
      sed --in-place -e 's|^Icon=.*|Icon=\${SNAP}/meta/gui/icon.png|' \
        "${SNAPCRAFT_PART_INSTALL}"/share/applications/net.poedit*.desktop

    stage-packages:
      # Called by Poedit
      - gettext

      # Required by Unity/GNOME?
      - libcanberra-gtk3-module

      - libcld2-0
      - libcpprest2.10
      - libgtkspell3-3-0
      - libice6
      - liblucene++0v5
      - libsecret-1-0
      - libsm6
      - libxxf86vm1

    filesets:
      executables:
        - bin/*
      files-in-stage-packages:
        - usr/*
      resources:
        - share/*

    stage:
      - $executables
      - $files-in-stage-packages
      - $resources

    prime:
      - $executables
      - $files-in-stage-packages
      - $resources

  wxwidgets:
    source: deps/wx

    build-packages:
      # Not used by Poedit
      #- libgl1-mesa-dev
      #- libglu1-mesa-dev
      #- libgstreamer1.0-dev
      #- libgstreamer-plugins-base1.0-dev
      #- libwebkit2gtk-4.0-dev

      - gettext
      - libcairo2-dev
      - libexpat1-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libnotify-dev
      - libpng-dev
      - libsecret-1-dev
      - libtiff5-dev
      - libxtst-dev
      - zlib1g-dev

    plugin: autotools
    override-build: |
      set -eu

      ./autogen.sh
      ./configure \
        --disable-shared \
        --disable-sound \
        --prefix="${SNAPCRAFT_STAGE}" \
        --with-gtk=3 \
        --without-opengl \
        --without-sdl \
        --enable-debug \
        --with-cxx=14 \
        --enable-stl
      make -j4
      make prefix="${SNAPCRAFT_PART_INSTALL}" install

    stage-packages:
      # For addr2line, required by wxWidgets error dialog
      - binutils

    filesets:
      autoconf-macros:
        - share/aclocal/*
      bakefiles:
        - share/bakefile/*
      files-from-stage-packages:
        - usr/*
      executables:
        - bin/*
      headers:
        - include/*
      libraries:
        - lib/*
      localizations:
        - share/locale/*
    stage:
      - $autoconf-macros
      - $executables
      - $files-from-stage-packages
      - $headers
      - $libraries
      - $localizations
    override-stage: |
      set -eu

      snapcraftctl stage

      # Fixup wrong wx-config link
      ln \
        --force \
        --relative \
        --symbolic \
        "${SNAPCRAFT_STAGE}"/lib/wx/config/gtk3-unicode-static-3.1 \
        "${SNAPCRAFT_STAGE}"/bin/wx-config
    prime:
      - $files-from-stage-packages
      - $localizations

  spellcheck-dictionaries:
    plugin: nil
    override-build: |
      set -eu

      # Download all dictionary packages, and extract to install prefix
      apt download $(apt-cache showpkg hunspell-dictionary | awk '/Pa/, /Reverse P/ {next} {print $1 | "sort"}')
      find -name '*.deb' | xargs --max-args=1 --replace={} --verbose dpkg-deb --extract {} ../install

    filesets:
      dictionaries:
        - usr/share/hunspell/*
        - usr/share/myspell/*
    stage:
      - $dictionaries
    prime:
      - $dictionaries
